### ISSUE TITLE
Why consult-lsp-marginalia?

### ISSUE THREAD

**Issue by minad** [gagbo/consult-lsp#18]
You can pass an `:annotate` argument to `consult--read`. Is this insufficient?

**Comment by gagbo** [comment]
Hello,

The first iteration of marginalia support came with #13 , and I didn’t like having `(require 'marginalia)` code inside the annotate function of `consult-lsp.el` basically.

Then, while trying to flesh out marginalia usage for all functions, I noticed that marginalia fully ignores the PREFIX part (`cadr`) of the affixation function that we pass for `:annotate`. This difference put me in a situation where I’d actually want 2 default `:annotate` functions :
- One for not-marginalia users, where I can put relevant information in the PREFIX (like the diagnostic level, or the line number for `file-symbols`)
- One for marginalia users, where I have to put everything in the SUFFIX (`caddr`)

Wasn’t really sure of the best way to do this, so I thought that a toggle for the 2 sets of `annotate` functions would be better. I then thought that a minor mode to be a good way to implement a toggle.

In the end, `consult-lsp-marginalia` only provides:
- another set of default `:annotate` functions,
- registration of annotators for `consult-lsp` categories (is that useless ?)
- Clearly defined and scoped marginalia dependency.

If it were only about the first one, I would probably not have split it in another file. For point 2, to be honest I don’t know, I never really went properly through marginalia documentation/code, so maybe I’m doing duplicate/useless work. For point 3, basically I wanted to have all marginalia-related code in its own closed location because of point 2.

I’m very open to suggestions though.
Have a nice day,
Gerry

**Comment by minad** [comment]
My point is mainly that Marginalia wasn't supposed to be used by
packages as long as you control the completion table yourself. If one
uses Marginalia for your own completion tables, it is better to just
provide an annotation-function or provide the :annotate argument to
consult--read in order to avoid introducing a dependency. For this use
case, Marginalia also doesn't bring huge benefits. One only gets access
to a handful of formatter functions which are not even part of the
public API.

On the other hand it is understandable that one wants to maintain a
coherent look which then requires you to use Marginalia, for the lack of
better formatting utilities for annotations provided by Emacs itself. I
am not very happy with the status quo here and I had hoped that one
could add an additional decoration-function to the completion metadata
which pushes the formatting to the completion UI. Then you wouldn't have
to use Marginalia to format multiple columns. Unfortunately the
discussion on emacs-devel died off. Maybe one should introduce a
metadata extension and add support to Vertico and Selectrum.

Regarding prefix annotations my opinion is that they shouldn't be used,
except for very rare circumstances like @iyefrat's icons. Therefore
Marginalia doesn't make use of them and always returns the empty string
as prefix.

**Comment by gagbo** [comment]
> to use the Marginalia annotator registry mechanism described in https://github.com/minad/marginalia#adding-custom-annotators-or-classifiers.

I'll try to do that then, and close the issue afterwards, thanks for your insights :)

**Comment by minad** [comment]
consult-lsp-marginalia seems gone by now?

**Comment by gagbo** [comment]
Yes it is, I didn't have the bandwidth to maintain it and it also hindered me when I had to change other things.
