### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by minad** [gagbo/consult-lsp#2]
Hi Gerry,

I went over your `consult-lsp` code. Here are a few comments, mostly pretty minor nitpicks. I think this looks good already, but I have not tried it yet. Did you have some more issues you want to discuss, in particular regarding the Consult APIs?

Daniel

-----

* Naming convention - `consult-lsp--` is probably better than `consult-lsp-diagnostics--`. But I've seen you organized everything under the `consult-lsp-diagnostics--` and `consult-lsp-symbols--` namespace, maybe that's okay?

https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L47

* Use `pcase` for this? Alternatively use an alist to keep the infor for both `consult-lsp-diagnostics--severity-to-level` and `consult-lsp-diagnostics--severity-to-type`?

https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L71-L75

* Use `rassq` on `consult-lsp-symbols--narrow` instead?

https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L194

* The `:predicate` is unnecessary. `consult--type-narrow` already supplies a special narrowing predicate, which is only used when `consult--narrow` is non-nil.
 
https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L322-L327
https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L144-L149

**Comment by gagbo** [comment]
Hi Daniel,

Thanks for the review, I've been meaning to use it for a few days and see where I have issues or not, I mostly did this for the `consult-lsp-diagnostics` method (I didn't want to have to use the treemacs version), and I'm pretty sure I missed some things that I'll uncover during usage.

> Naming convention - consult-lsp-- is probably better than consult-lsp-diagnostics--

I have no strong opinion on this one, I think I did the latter because it made more sense to me to put the "helpers" of each command under their own namespace, but there's probably code that can be mutualized, so `consult-lsp--` would make more sense.

> Alternatively use an alist to keep the infor for both consult-lsp-diagnostics--severity-to-level and consult-lsp-diagnostics--severity-to-type

Yes, I should definitely do this. I actually wonder how I could make the use of narrow-keys easier in the code...

> Use rassq on consult-lsp-symbols--narrow instead?

rassq is probably the answer looking at its name. I didn't think of looking for such a function


> The :predicate is unnecessary. consult--type-narrow already supplies a special narrowing predicate, which is only used when consult--narrow is non-nil.

I thought the predicate bit was necessary for some reason I forgot why.


I think I have a bug with how async candidates are updated with `consult-lsp-symbols`, but it's something I'll fix when I actually reproduce the issue consistently.

Also, I've been trying to sort the candidates of `consult-lsp-diagnostics` by ascending severity
https://github.com/gagbo/consult-lsp/blob/04462d2d11dff74002ddc828a732b8b8b2b8145d/consult-lsp.el#L60-L66
 (because `Error` is 1 and `info` is 3), but ever since I added the :title argument to the `consult--read` call it seems that I lost the ordering and instead I have this weird "Warnings (2) then Hints (4) then Errors(1)" ordering in the initial minibuffer, and I wonder what's wrong with my approach
 
Thanks again for looking out,
Gerry

**Comment by minad** [comment]
> I have no strong opinion on this one, I think I did the latter because it made more sense to me to put the "helpers" of each command under their own namespace, but there's probably code that can be mutualized, so consult-lsp-- would make more sense.

I would go with the standard convention for modules. If you split it in two modules your convention is good.

> Yes, I should definitely do this. I actually wonder how I could make the use of narrow-keys easier in the code...

Yeah, narrowing is a bit of a hassle. For every command which uses this you have define custom keys apply them to all candidates and so on. But using the `consult--type-*` helpers this already got a bit easier. Furthermore the `consult--multi` based commands also get narrowing basically for free. Do you mean something specific which could be simplified?

> I thought the predicate bit was necessary for some reason I forgot why.

It is usually not necessary if you use `consult--type-narrow`. Only if you want to use a more complicated predicate condition, e.g., in the case of `consult-mode-command`, the global minor mode commands are initially hidden. In order to implement this hiding one needs the special predicate.

> Also, I've been trying to sort the candidates of consult-lsp-diagnostics by ascending severity
> (because Error is 1 and info is 3), but ever since I added the :title argument to the consult--read call it seems that I lost the ordering and instead I have this weird "Warnings (2) then Hints (4) then Errors(1)" ordering in the initial minibuffer, and I wonder what's wrong with my approach

This should work. The original ordering is preserved by the grouping/titles. If you figure out what the issue is please let me know!

**Comment by minad** [comment]
Can be closed I guess?

**Comment by gagbo** [comment]
yeah sure, thanks for the help ! I kept it open just in case I found out my issue with diagnostics ordering quickly, but obviously that didn’t happen (could even try to repro yet).

We’ll see if I encounter it later !
