### ISSUE TITLE
Break lines

### ISSUE THREAD

**Issue by bkchr** [gagbo/consult-lsp#22]
Hey, is it possible to somehow break the line from a message? I mean, I can only see parts of the message and the rest is truncated. Is there maybe an option that I could enable?

**Comment by gagbo** [comment]
It's not something that I made available because I wasn't sure that displaying multi-line diagnostics was possible in minibuffer completion, and I didn't have time to look into that. That's why I [always replace newlines](https://github.com/gagbo/consult-lsp/blob/aaa9a31bc82259d743186c53d8b01f043c6fec13/consult-lsp.el#L235) in diagnostics. I know that Rust errors can be quite long, that's also kind of a pain point for me, but I'll need to go deeper into consult and minibuffer completion to see what's possible

**Comment by bkchr** [comment]
Okay ty for your answer :)

**Comment by gagbo** [comment]
I think it's actually not easy to do:

I learned that I should not do the preprocessing myself (i.e. stripping newlines and replacing them with spaces), but even then, the minibuffer completion doesn't look like it really likes to have multi-line completions.

The packages that usually handle this specific issue ("how to render candidates that span multiple lines ?") are the "Completion UI" ones, so directly vertico,selectrum,ivy,helm etc.

Currently, as far as I understand:
- selectrum [replaces](https://github.com/raxod502/selectrum/blob/76e63d0b5d9d48768208f83ab1d2b2adf373a264/selectrum.el#L311) newlines with the raw escape sequence `\n` with a different face (and ends up truncating the message and showing the line count)
- vertico [replaces](https://github.com/minad/vertico/blob/f3f55e4f5923fe2108a59eedb68e9989d1cef151/vertico.el#L473) newlines with a unicode char by default as well.

I think there are currently no solution to that issue, as both seems to have given up; otherwise I assume there would be some form of `max-candidates-lines` variable to be able to show 3/4 line candidates or something.

So the workarounds that I know around that would be either to:
- use lsp-treemacs, it uses a treemacs buffer to display the error list, so there are no single-line constraint and everything should be displayed, or
- look around helm. It's admittedly a much bigger change in the package stack, and I'm really not sure it would solve anything (checking helm-lsp would probably help); but as far as I remember, helm also uses its own buffer, so maybe completion interface limitations don't apply either.

I'll probably need to talk a little bit with minad to confirm this, but that's what I understand right now

**Comment by gagbo** [comment]
Closing this as I lost a bit of context and I don't expect to have time soon to somehow make this configurable.
