### ISSUE TITLE
Problems with rng-uri-file-name

### ISSUE THREAD

**Issue by gessen** [gagbo/consult-lsp#3]
This function is required neither by `lsp` nor `consult` so without explicitly loading it, Emacs complains about an unknown function. After loading `rng-uri.el`, the function will emit error when used with C++ server. The reason for that is that standard library headers are placed on Linux in `/usr/include/c++/<version>` and the input for `rng-uri-file-name` will be e.g. `file:///usr/include/c%2B%2B/10.2.0/vector`. The presence of %2B for some reason makes [this regex](https://github.com/emacs-mirror/emacs/blob/master/lisp/nxml/rng-uri.el#L71) non-matching.

**Comment by gagbo** [comment]
Thanks for the precise report. I think 
- I'll add rng-uri to the required packages (I guess I should really build a clean emacs sandbox with only the dependencies for that, I have to remember doing it with [alphapapa's script](https://github.com/alphapapa/emacs-sandbox.sh))
- I will look for a function to decode uri as well, it's really weird that it doesn't match the regex otherwise; `%2B` definitely matches `%[[:xdigit:]]{2}`

**Comment by gagbo** [comment]
That regex not working is really weird
```lisp
(string-match "\\`\\(?:%[[:xdigit:]]{2}\\)*\\'" "%2B%2B") ; => nil
(string-match "\\`\\(?:%[[:xdigit:]]{2}\\)*" "%2B%2B") ; => 0
```
I have no explanation on this one for now, I'll keep looking

**Comment by gessen** [comment]
I have the same results. It works correctly with other regex implementation, so it's puzzling why it cannot match. Anyway, thanks for the quick fix!

**Comment by gagbo** [comment]
I asked for help on irc, and it looks like the regex is wrong, it should escape the braces : `{2} => \\{2\\}`
