### ISSUE TITLE
Is there a way to filter the results?

### ISSUE THREAD

**Issue by furkanusta** [gagbo/consult-lsp#31]
When I run `consult-lsp-symbols` I see system methods/class due to the way C++ include's works (I suppose). I'd like to filter those by checking if source files belong to the project. I've checked annotate functions but I do not think they provide the functionality. 

I am not sure how much of the work is being done by LSP server, emacs-lsp, consult and this package. Feel free to close this, if it cannot be done at this level easily.

**Comment by gagbo** [comment]
For all LSP commands, you can use the ["narrow" keys](https://github.com/minad/consult#narrowing-and-grouping) from consult to reduce the set of results to certain types. If you want to see all the categories, use `C-h v consult-lsp-symbols-narrow`.

`lsp-symbols` in particular, has a specific pattern on top of that [(because like `consult-grep`, it sends user input to an external process - the LSP server - to get the results)](https://github.com/minad/consult#asynchronous-search). So you can also split your query with the `async-separator` (`#` by default if I remember correctly) and everything _after_ the `#` will just be used to filter the current candidates you have in your minibuffer (so you can use it to type some filepath and filter everything by the path). Everything that is _before_ the `#` will be sent to refine the query to the LSP server.

**Comment by gagbo** [comment]
You should be able to use `#K#!usr` can't you ? The part that goes after the second `#` is going to be used by your own filtering mechanisms.[ I use orderless and I set it up so that `!` as a prefix acts as a negation of the pattern](https://github.com/oantolin/orderless#style-dispatchers), so I can ignore these things using `!usr` for example

**Comment by furkanusta** [comment]
Oh, I had orderless in my setup but I never tweaked it and this worked like a charm. Thanks.
