### ISSUE TITLE
consult-lsp--file-symbols-candidates: No symbols

### ISSUE THREAD

**Issue by Peter-Chou** [gagbo/consult-lsp#33]
when I run consult-lsp-file-symbols, it showed no symbols. but I got right infos with consult-imenu.     

![image](https://user-images.githubusercontent.com/28672146/192095984-e5419ec9-2e59-4c4d-9876-433dce5b4e01.png)

consult-lsp-file-symbols has a big advantage to consult-imenu due to the narrowing mechanism. I really hope this command could run as expected. thx.

**Comment by gagbo** [comment]
Hello,

It looks like your LSP server either hasn't been started, or that it cannot deal with the current file. `consult-imenu` only uses `imenu`, which is basically a regexp-based feature. The "No symbols" message means the LSP server didn't give any response to the `documentSymbols` request.

Cheers

**Comment by Peter-Chou** [comment]
@gagbo, thanks for the quick reply. I used pyright python language server and i works normal with `consult-lsp-symbols`.

**Comment by gagbo** [comment]
No, there are 2 calls, 
- For consult-lsp-symbols it is `workspace/symbols` https://github.com/gagbo/consult-lsp/blob/19606a03cf854e1b0930c4526ed92c4560dccdc2/consult-lsp.el#L326
- For consult-lsp-file-symbols, it is `documentSymbols` https://github.com/gagbo/consult-lsp/blob/19606a03cf854e1b0930c4526ed92c4560dccdc2/consult-lsp.el#L497

I didn't check the protocol in a while to see if it changed, but theoretically that should not be a problem, so somehow pyright doesn't want to answer the documentSymbols call it seems

**Comment by sebastiansturm** [comment]
just today I noticed I'd get the same error (with a language server that definitely returned symbols), but in my case it was because `consult-lsp--flatten-document-symbols` doesn't respect `lsp-use-plists`. Can open a small PR the next few days though for my personal use I'd also have to change the default filtering because having all levels of symbols presented as a flat list seems overwhelming to me. (also, there was some error trying to invoke `consult-lsp--file-symbols--transformer` if symbols spanned multiple lines; in that case `cend` can be smaller than `cbeg`)

**Comment by gagbo** [comment]
All good points, it's indeed more likely that the heart of the issue is the use of `lsp-use-plists`, I forgot to check the code for compatibility, and the bug with `cend < cbeg` is also an issue because we try to use the same line for everything. Thanks for the report

**Comment by gagbo** [comment]
Both issues should be fixed now with the commit above ^. I also tagged it so eventually it'll also hit MELPA stable for the mad lads who trust it.

Don't hesitate to comment if that doesn't work
